tabela_erros_completa = {
    'ESCC0000': 'Processamento realizado com sucesso.',
    'ESCC0009': 'Órgão na CIP está diferente do Participante Administrado informado.',
    'ESCC0010': 'Ente não cadastrado.',
    'ESCC0011': 'Órgão não cadastrado.',
    'ESCC0012': 'Ente não está ativo.',
    'ESCC0013': 'Órgão não está ativo.',
    'ESCC0014': 'Órgão inválido ao Ente informado.',
    'ESCC0015': 'Número do CPF inválido.',
    'ESCC0016': 'Número do RG obrigatório.',
    'ESCC0017': 'Valor da parcela deve ser maior que zero.',
    'ESCC0018': 'Dados de cadastro não localizados.',
    'ESCC0019': 'Indicador de janelamento fora do domínio estabelecido.',
    'ESCC0020': 'Data de nascimento inválida.',
    'ESCC0021': 'E-mail do servidor incorreto.',
    'ESCC0022': 'Tipo de Vínculo não cadastrado.',
    'ESCC0023': 'Mês e Ano de vencimento da parcela inválidos.',
    'ESCC0024': 'Data de Nomeação/Admissão inválida.',
    'ESCC0025': 'Data final do contrato temporário inválida.',
    'ESCC0026': 'Data final da averbação obrigatória.',
    'ESCC0027': 'Valor da margem bruta deve ser maior do que zero.',
    'ESCC0028': 'Mês de referência da margem diferente do mês do calendário cadastrado.',
    'ESCC0029': 'Valor Total do Contrato deve ser igual à soma das tarifas e valor liberado.',
    'ESCC0030': 'Matrícula ou Identificação em duplicidade.',
    'ESCC0031': 'Consignatário não cadastrado.',
    'ESCC0032': 'Consignatário não está ativo.',
    'ESCC0033': 'Consignatário diferente do Participante Administrado.',
    'ESCC0034': 'Consignatário não está vinculado ou habilitado no Órgão.',
    'ESCC0035': 'Espécie não cadastrada.',
    'ESCC0036': 'Espécie não está vigente.',
    'ESCC0037': 'Espécie não está vinculada ao Consignatário.',
    'ESCC0038': 'Espécie permite somente quantidade de parcelas maior do que zero.',
    'ESCC0039': 'Quantidade total de parcelas maior do que o máximo permitido para a espécie.',
    'ESCC0040': 'Espécie bloqueada.',
    'ESCC0041': 'Espécie inativa ou fora da vigência.',
    'ESCC0042': 'Quantidade total de parcelas deve ser igual a 1 para espécie com o tipo de parcelamento igual a "Único".',
    'ESCC0043': 'Vencimento da primeira parcela ou carência inicial (Mês e Ano) não permitido para',
    'ESCC0044': 'Mês/Ano do primeiro desconto está fora do período de carência permitido para a espécie.',
    'ESCC0045': 'Dia do vencimento da parcela inválido.',
    'ESCC0046': 'Data de Início da averbação inválida.',
    'ESCC0047': 'Data de Início da averbação deve ser menor ou igual à data de referência.',
    'ESCC0048': 'O valor da parcela deve ser maior ou igual ao valor mínimo de parcela permitido para',
    'ESCC0049': 'Valor da margem indisponível.',
    'ESCC0050': 'Margem insuficiente.',
    'ESCC0054': 'Número Único da Averbação inválido.',
    'ESCC0055': 'Número único de averbação não vinculado ao CPF informado.',
    'ESCC0056': 'Alongamento não permitido para espécie.',
    'ESCC0057': 'Indicador de alongamento fora do domínio estabelecido.',
    'ESCC0058': 'Obrigatório informar parcela(s) de janelamento.',
    'ESCC0059': 'Parcela(s) de janelamento não deve(m) ser informada(s). Indicador de janelamento',
    'ESCC0060': 'Número único da averbação não pertence ao Consignatário.',
    'ESCC0061': 'Mês e Ano de vencimento da parcela deve ser maior que o Vencimento da 1ª parcela ou',
    'ESCC0062': 'Quantidade de parcela(s) deve ser maior do que zero.',
    'ESCC0063': 'Número da parcela informada para desaverbação é maior que o número total de parcelas.',
    'ESCC0064': 'Mês e Ano de vencimento da Parcela ou Número da Parcela devem ser informados no',
    'ESCC0065': 'Taxa Nominal deve ser maior ou igual a zero.',
    'ESCC0066': 'Taxa CET deve ser maior ou igual a zero.',
    'ESCC0067': 'Valor Liberado deve ser maior ou igual a zero.',
    'ESCC0068': 'Valor das tarifas do contrato deve ser maior ou igual a zero.',
    'ESCC0069': 'Valor dos tributos do contrato deve ser maior ou igual a zero.',
    'ESCC0070': 'Valor dos encargos do contrato deve ser maior ou igual a zero.',
    'ESCC0071': 'Valor Total do Contrato, incluindo tarifas e tributos, deve ser maior ou igual a zero.',
    'ESCC0072': 'Averbação já registrada.',
    'ESCC0073': 'Averbação baixada.',
    'ESCC0074': 'Averbação Cancelada.',
    'ESCC0075': 'Desaverbada.',
    'ESCC0076': 'Averbação refinanciada.',
    'ESCC0077': 'Averbação bloqueada sem a liberação de margem.',
    'ESCC0078': 'Averbação bloqueada com a liberação de margem.',
    'ESCC0079': 'Averbação cancelada automaticamente.',
    'ESCC0080': 'Averbação cancelada por Refinanciamento.',
    'ESCC0081': 'Reserva de averbação cancelada por decurso de prazo.',
    'ESCC0082': 'Averbação com parcela provisionada. Parcela sem débito na folha de pagamento.',
    'ESCC0084': 'Averbação em negociação.',
    'ESCC0085': 'Quantidade total de parcelas deve ser igual a zero para espécie com o tipo de',
    'ESCC0086': 'Parcela já foi processada por outro arquivo e não pode ser reprocessada.',
    'ESCC0089': 'Órgão não cadastrado.',
    'ESCC0090': 'Número de Parcela não foi localizado.',
    'ESCC0091': 'Parcela já enviada para processamento em folha de pagamento não pode ser cancelada.',
    'ESCC0092': 'Parcela já cancelada.',
    'ESCC0093': 'Parcela em situação de "alongada".',
    'ESCC0094': 'Valor debitado é maior que o valor da parcela.',
    'ESCC0095': 'Identificação do Motivo da Consignação inválida.',
    'ESCC0100': 'Não é permitido informar Averbação em situação de reserva.',
    'ESCC0101': 'Tipo de Parcelamento fora do domínio.',
    'ESCC0102': 'Data fim da taxa inválida.',
    'ESCC0103': 'Motivo da Desaverbação informado fora do domínio estabelecido.',
    'ESCC0104': 'Vencimento da parcela inválido.',
    'ESCC0105': 'Situação Cadastral inválida.',
    'ESCC0107': 'Identificação do Motivo da Alteração da Parcela inválida.',
    'ESCC0108': 'Espécie não permite alteração.',
    'ESCC0109': 'Para a alteração da parcela, informar o valor a ser alterado ou a quantidade total de parcelas.',
    'ESCC0110': 'Data Início da taxa deve ser maior que a data atual do sistema.',
    'ESCC0111': 'Data Início da taxa inválida.',
    'ESCC0112': 'Data fim da taxa deve ser maior que a data início.',
    'ESCC0113': 'Prazo da taxa deve ser maior do que zero.',
    'ESCC0114': 'Dados Cadastrais não localizados para efetuar a transferência.',
    'ESCC0115': 'CPF divergente entre averbação origem e averbação destino.',
    'ESCC0116': 'Encontrados múltiplos registros com a mesma identificação ou matrícula. Realize nova',
    'ESCC0117': 'Quantidade máxima de averbações para o mesmo consignatário excedida.',
    'ESCC0118': 'O limite máximo de averbações permitidas para a identificação ou matrícula foi atingido.',
    'ESCC0119': 'Quantidade total de parcelas não está dentro dos meses entre a data da averbação e o fim',
    'ESCC0121': 'Janelamento não permitido para parcela única.',
    'ESCC0122': 'Parcela da averbação já com desconto efetuado.',
    'ESCC0123': 'Registro(s) não localizados para o filtro informado.',
    'ESCC0125': 'Órgão não está ativo.',
    'ESCC0126': 'Órgão informado no campo "De" não cadastrado.',
    'ESCC0127': 'Órgão informando no campo "De" não está ativo.',
    'ESCC0128': 'Órgão informado no campo "Para" não está cadastrado.',
    'ESCC0129': 'Órgão informado no campo "Para" não está ativo.',
    'ESCC0130': 'Motivo da Transferência inválido.',
    'ESCC0131': 'Transferência da(s) averbação(ões) não realizada. Identificado mais de um provimento vinculado à matricula ou identificação.',
    'ESCC0132': 'Margem indisponível para finalizar a averbação.',
    'ESCC0134': 'Número do contrato já sendo utilizado por outra averbação pelo Consignatário.',
    'ESCC0135': 'Excedido o limite diário da consulta de margem.',
    'ESCC0136': 'Mês/Ano de referência divergentes entre os registros.',
    'ESCC0137': 'Número da parcela não localizada.',
    'ESCC0138': 'Não há taxa vigente para a prazo de parcela informado.',
    'ESCC0139': 'Valor total incorreto para a quantidade e valor da parcela.',
    'ESCC0142': 'Valor total deve ser maior ou igual a zero.',
    'ESCC0143': 'Valor da parcela final da averbação deve ser maior que zero e menor ou igual ao valor da',
    'ESCC0144': 'Não foi possível cancelar a averbação. Número único da averbação informado não está vinculado a um refinanciamento.',
    'ESCC0145': 'Não foi possível cancelar a averbação. A data entre a inclusão do refinanciamento e a data',
    'ESCC0146': 'Não foi possível cancelar o refinanciamento. Primeira parcela da averbação já foi enviada',
    'ESCC0147': 'Averbação cancelada por motivo estorno de refinanciamento.',
    'ESCC0148': 'Reserva não finalizada por insuficiência de margem.',
    'ESCC0150': 'Número da parcela ou o vencimento da parcela obrigatório.',
    'ESCC0151': 'Informar somente o número da parcela OU o vencimento da parcela.',
    'ESCC0152': 'Parcela já desaverbada.',
    'ESCC0153': 'Não foi identificada uma parcela para o Mês/Ano informado.',
    'ESCC0155': 'Motivo da desaverbação fora dos domínios estabelecidos.',
    'ESCC0156': 'Mês/Ano de primeiro desconto informado não permitido. Parcela já processada.',
    'ESCC0157': 'Calendário de processamento não cadastrado.',
    'ESCC0158': 'A data de início do contrato é maior do que o limite máximo de dias estabelecido.',
    'ESCC0159': 'Vencimento da 1ª parcela (Mês e Ano) deve ser maior ou igual à referência da folha.',
    'ESCC0160': 'Vencimento da 1ª parcela (Mês e Ano) deve ser maior ou igual ao mês de competência da',
    'ESCC0161': 'Refinanciamento não realizado. Averbação não atingiu a quantidade mínima de parcelas processadas estabelecida pelo Ente Consignante.',
    'ESCC0164': 'Situação cadastral da identificação ou matrícula não permite alteração.',
    'ESCC0170': 'Alteração de parcelas não realizada. A quantidade de parcela informada é igual à atual.',
    'ESCC0173': 'O servidor com as informações de origem não foi localizado no cadastro e a transferência',
    'ESCC0174': 'Alteração de parcelas não realizada. Tipo de parcelamento não permite alteração.',
    'ESCC0175': 'Alteração de parcelas não realizada. Quantidade informada é menor que a quantidade de',
    'ESCC0177': 'Consignatário não está ativo na CIP.',
    'ESCC0178': 'Consignatário não está ativo no Ente.',
    'ESCC0179': 'Consignatário com situação de "Descredenciado" no Ente.',
    'ESCC0180': 'Processamento não realizado. Averbação está em processo de aprovação.',
    'ESCC0181': 'Cancelamento do refinanciamento não permitido pelo Ente.',
    'ESCC0185': 'Tipo de Parcelamento informado não permitido para a espécie.',
    'ESCC0186': 'Parcelamento único não permite desaverbação por tipo de "parcela". Enviar solicitação',
    'ESCC0187': 'CPF inexistente.',
    'ESCC0188': 'Identificação ou matrícula inexistente.',
    'ESCC0189': 'Identificação ou matrícula divergente do número cadastrado no Órgão.',
    'ESCC0190': 'Número da averbação não vinculado ao Ente.',
    'ESCC0191': 'Número da averbação não está vinculado ao Órgão.',
    'ESCC0192': 'Data informada inválida.',
    'ESCC0193': 'Data informada é superior à data de vigência do contrato.',
    'ESCC0200': 'Consignatário com a situação cadastral impeditiva para operação.',
    'ESCC0201': 'CPF não possui averbação vinculada ao Consignatário.',
    'ESCC0202': 'Identificação ou matrícula inexistente.',
    'ESCC0203': 'Identificação ou matrícula informado não possui averbação(ões) vinculada(s) ao',
    'ESCC0204': 'Número Único da Averbação não está vinculado ao CPF, Consignatário e Órgão.',
    'ESCC0205': 'Número único da averbação não está vinculado ao CPF informado.',
    'ESCC0206': 'Data Fim da averbação inválida.',
    'ESCC0207': 'A requisição excedeu a quantidade de linhas permitidas no resultado. Realize um novo',
    'ESCC0208': 'Vago (era usado no 14)',
    'ESCC0209': 'Espécie não possui taxa CET vigente informada pelo Consignatário.',
    'ESCC0210': 'Espécie não possui taxa Nominal vigente informada pelo Consignatário.',
    'ESCC0211': 'Espécie não possui taxa CET e Nominal vigente informadas pelo Consignatário.',
    'ESCC0212': 'Produto da espécie associada não está habilitado para o Ente.',
    'ESCC0213': 'Consignatário ultrapassou a quantidade de averbações permitidas para o produto',
    'ESCC0214': 'Mês/Ano informado inválido.',
    'ESCC0215': 'Espécie não está vinculada ao tipo de processo e arquivo enviado.',
    'ESCC0216': 'Produto informado não está vinculado ao Ente.',
    'ESCC0217': 'Espécie deve estar ativa ou vinculada ao Produto.',
    'ESCC0221': 'Tipo de envio da margem do Ente é "somatória" e o produto informado não é de',
    'ESCC0222': 'Número do Contrato da IF informado na Prévia diferente do Número do Contrato da IF informado na Averbação com Prévia.',
    'ESCC0226': 'Prévia recusada. Não existe averbação com situação "Ativa".',
    'ESCC0236': 'Funcionalidade permite informar somente operações de espécies financeiras.',
    'ESCC0237': 'Produto inválido.',
    'ESCC0238': 'Vago',
    'ESCC0239': 'Vago',
    'ESCC0240': 'Complemento não realizado. Averbação não está ativa.',
    'ESCC0241': 'Data fim da averbação deve ser maior que a data atual.',
    'ESCC0243': 'Espécie não permite refinanciamento.',
    'ESCC0244': 'Espécie da averbação de Origem não está associada à nova Espécie.',
    'ESCC0246': 'Campo sexo deve ser preenchido com "Masculino" ou "Feminino".',
    'ESCC0247': 'UF inválida.',
    'ESCC0248': 'Cadastro da margem recusado. Ente não permite o envio de mais de uma margem.',
    'ESCC0249': 'Produto não vinculado ao Ente.',
    'ESCC0250': 'CEP inválido.',
    'ESCC0253': 'Prazo da taxa obrigatório.',
    'ESCC0254': 'vazio',
    'ESCC0255': 'Órgão na CIP está diferente da Identificação do Órgão cadastrado.',
    'ESCC0256': 'Taxa Nominal informada maior do que a taxa máxima cadastrada para a espécie.',
    'ESCC0257': 'Taxa deve ser maior do que zero.',
    'ESCC0258': 'Taxa CET informada maior do que a taxa máxima cadastrada para a espécie.',
    'ESCC0266': 'Espécie não permite desaverbação de parcela.',
    'ESCC0267': 'Valor informado na prévia deve ser igual ou menor do que o valor de parcela averbado.',
    'ESCC0268': 'Número de Telefone inválido.',
    'ESCC0270': 'Valor da parcela informado é menor do que valor mínimo permitido para a Espécie.',
    'ESCC0273': 'Ente sem adesão à Funcionalidade.',
    'ESCC0274': 'Conciliação da parcela não realizada. Número único da averbação não foi enviada na',
    'ESCC0275': 'Identificação ou número do CNPJ do Órgão obrigatório.',
    'ESCC0276': 'Consignatário não está vinculado ao Ente.',
    'ESCC0277': 'Data de averbação do legado deve ser menor do que a data atual.',
    'ESCC0278': 'Espécie não está vinculada ao Produto.',
    'ESCC0279': 'Número Único da Averbação não está vinculado à Identificação ou matrícula informada.',
    'ESCC0280': 'Taxa Juros dever ser maior do que "zero".',
    'ESCC0281': 'Espécie não permite manutenção no controle da taxa de juros.',
    'ESCC0282': 'Parcela já enviada para processamento em folha de pagamento.',
    'ESCC0283': 'Horário da Averbação no legado inválido.',
    'ESCC0284': 'O Horário de inclusão da Averbação no sistema legado deverá ser menor que o horário',
    'ESCC0285': 'Número do CPF e/ou Identificação informado)s) não pertencem ao Consignatário no Ente.',
    'ESCC0286': 'Número único da Averbação não localizado para o número do Contrato IF informado.',
    'ESCC0287': 'Situação da averbação inválida.',
    'ESCC0288': 'CNPJ do Órgão não corresponde à Identificação informada.',
    'ESCC0289': 'Órgão não vinculado ao CPF.',
    'ESCC0290': 'Espécie(s) vinculada(s) ao consignatário não está(ão) relacionada(s) ao produto.',
    'ESCC0291': 'Identificação ou matrícula não autoriza contratação para a espécie informada.',
    'ESCC0293': 'Alteração não realizada. O valor de parcela informado é igual ao valor atual.',
    'ESCC0294': 'Alteração não realizada. Averbação em situação "gestão administrativa".',
    'ESCC0295': 'Refinanciamento não realizado. Averbação em situação "Gestão administrativa".',
    'ESCC0296': 'Valor informado maior do que o permitido. Valor da reserva de margem alterado por',
    'ESCC0297': 'Usuário bloqueado por excesso de consultas.',
    'ESCC0298': 'Motivo de estorno aceito somente para parcelas já conciliadas.',
    'ESCC0299': 'Mês/Ano informado não corresponde ao Número da Parcela informada.',
    'ESCC0302': 'Para motivos que indiquem "Desconto efetuado", informar valor de parcela maior do que',
    'ESCC0303': 'Para motivos que indiquem "Desconto não efetuado", informar valor da parcela igual a "zero".',
    'ESCC0304': 'Não existe Ordenação do Legado do Órgão na CIP.',
    'ESCC0305': 'CNPJ Base do Órgão não vinculado ao CPF e Identificação informados.',
    'ESCC0306': 'Participante Administrado deve ser o Órgão do Servidor ou o Consignatário detentor da',
    'ESCC0307': 'Tipo de Operação inválido.',
    'ESCC0308': 'Número único da Averbação Legado não informado.',
    'ESCC0309': 'Número único da averbação não localizado.',
    'ESCC0310': 'Situação da Carga do Legado não permitida para o "Tipo de Operação".',
    'ESCC0311': 'Número único da Averbação no Consignatário já utilizado.',
    'ESCC0312': 'Indicador de Alongamento obrigatório.',
    'ESCC0313': 'Quantidade total de parcelas obrigatório.',
    'ESCC0314': 'Quantidade de parcelas processadas obrigatório.',
    'ESCC0315': 'Quantidade de parcelas processadas deve ser menor que a quantidade total de Parcelas.',
    'ESCC0316': 'Dia do vencimento obrigatório.',
    'ESCC0317': 'Indicador de carência obrigatório.',
    'ESCC0318': 'Indicador de Carência fora do domínio.',
    'ESCC0319': 'Espécie não permite carência.',
    'ESCC0320': 'Não é permitido informar Mês/Ano de carência. Indicador de carência igual a "N".',
    'ESCC0321': 'Data de início obrigatória.',
    'ESCC0322': 'Data de averbação no legado obrigatório.',
    'ESCC0323': 'Data da averbação no legado inválida.',
    'ESCC0324': 'Horário da averbação no legado obrigatório.',
    'ESCC0325': 'Motivo da averbação Legado inválido.',
    'ESCC0326': 'Indicador de "Histórico de Parcelas" inválido.',
    'ESCC0327': 'Não é permitido informar "Parcelas Históricas". Indicador informado igual a "N".',
    'ESCC0328': 'Número da Parcela do Histórico deve ser menor ou igual à quantidade de parcelas processadas.',
    'ESCC0329': 'Número da parcela Histórico inválido. Parcela já processada.',
    'ESCC0331': 'Mês/Ano da Parcela Histórico informado deve ser menor que o Mês/Ano de Referência do Órgão.',
    'ESCC0332': 'Mês/Ano da Parcela Histórico já possuí Parcela gerada.',
    'ESCC0333': 'Valor da Parcela Histórico deve ser maior do que zero.',
    'ESCC0336': 'Valor pago da Parcela Histórico deve ser maior ou igual a zero.',
    'ESCC0338': 'Situação da Parcela Histórico informada fora do domínio.',
    'ESCC0339': 'Grupo de "Parcelas em janelamento" deve ser informado para "Indicador de Parcela',
    'ESCC0340': 'Mês/Ano de Janelamento não é permitido. Parcela enviada para processamento em folha',
    'ESCC0341': 'Mês/Ano de Janelamento informado em duplicidade.',
    'ESCC0342': 'Mês/Ano de primeiro desconto deve ser informado para "Indicador de Carência" igual a',
    'ESCC0343': 'Grupo de "histórico de parcelas alongada" deve ser informado para "Indicador de histórico',
    'ESCC0344': 'Mês/Ano da Parcela Histórico é inválido.',
    'ESCC0345': 'Tipo de Processo da Espécie não permitido para a averbação.',
    'ESCC0346': 'Tipo de averbação não permitido para Órgão.',
    'ESCC0349': 'Participante informado deve ser um Ente.',
    'ESCC0350': 'Ente informado inválido.',
    'ESCC0351': 'CNPJ inválido para o Consignatário.',
    'ESCC0352': 'CNPJ do Consignatário já está cadastrado no Ente.',
    'ESCC0353': 'Natureza do Consignatário fora do domínio.',
    'ESCC0354': 'CPF do responsável inválido.',
    'ESCC0355': 'Número do Consignatário já cadastrado no Ente.',
    'ESCC0356': 'Obrigatório vincular um Órgão ao Consignatário.',
    'ESCC0357': 'Obrigatório vincular uma espécie ao Consignatário.',
    'ESCC0358': 'Órgão(s) não existe(m) no Ente.',
    'ESCC0359': 'Espécie(s) não existe(m) no Ente.',
    'ESCC0360': 'Não é permitido realizar carga do legado fora do período estabelecido pelo Órgão.',
    'ESCC0361': 'E-mail do responsável inválido.',
    'ESCC0362': 'Data de recadastramento inválida.',
    'ESCC0363': 'Data de credenciamento inválida.',
    'ESCC0364': 'Data de Fim do Mandato inválida.',
    'ESCC0365': 'Data de Auditoria inválida.',
    'ESCC0366': 'Consignatário não cadastrado. Razão Social obrigatório.',
    'ESCC0367': 'Consignatário não cadastrado. Nome Reduzido obrigatório.',
    'ESCC0368': 'Consignatário não cadastrado. Natureza obrigatório.',
    'ESCC0369': 'Consignatário não cadastrado. Endereço obrigatório.',
    'ESCC0370': 'Código da espécie já cadastrado.',
    'ESCC0371': 'Produto inválido.',
    'ESCC0372': '"Quantidade máxima de averbações por Consignatário" deve ser menor ou igual à',
    'ESCC0373': 'Parcelamento Máximo não deve ser informado para o Tipo de Parcelamento "indeterminado".',
    'ESCC0374': 'Parcelamento Máximo deve ser igual a "1" para o tipo de Parcelamento igual à "Único".',
    'ESCC0375': 'Parcelamento máximo deve ser informado no intervalo entre "1 e 9999", conforme limite estabelecido na espécie.',
    'ESCC0376': 'Indicador de permissão "Averbar sem Margem" inválido.',
    'ESCC0377': 'Indicador de permissão "Carência de Início de Débito" inválido.',
    'ESCC0378': 'Quantidade de meses de carência não deve ser informada. Indicador de Carência de Início',
    'ESCC0379': 'Quantidade de meses de carência deve ser informada dentro do intervalo de "1 a 99".',
    'ESCC0380': 'Taxa de custeio deve ser informada no intervalo de "0 a 99,99999".',
    'ESCC0381': 'Ordem de Prioridade inválida.',
    'ESCC0382': 'Indicador de "validação de valor mínimo" inválido.',
    'ESCC0383': '"Valor Mínimo" obrigatório. Indicador de validação de Valor Mínimo igual a "Não".',
    'ESCC0384': 'Valor Mínimo de Parcela deve ser maior do que zero.',
    'ESCC0385': 'Indicador "Alongamento" inválido.',
    'ESCC0386': 'Indicador "Débito Parcial" inválido.',
    'ESCC0387': 'Tipo de valor inválido.',
    'ESCC0388': 'Valor mínimo deve ser menor ou igual a "100" quando o “Tipo de Valor” igual à',
    'ESCC0389': 'Tipo de valor não deve ser informado quando Indicador de "Valor Mínimo" igual a "Não".',
    'ESCC0390': 'Indicador "Alterar Quantidade de Parcelas e Valor" inválido.',
    'ESCC0391': 'Indicador "Alterar sem Margem" não deve ser informado quando o Indicador "Alterar',
    'ESCC0392': 'Indicador "Alteração sem Margem" deve ser informado quando o indicador "Alterar',
    'ESCC0393': 'Indicador "Perda de Prioridade" não deve ser informado quando o Indicador "Alterar',
    'ESCC0394': 'Indicador "Perda de Prioridade" deve ser informado quando o indicador "Quantidade de Parcelas e Valor" for igual a "Sim".',
    'ESCC0395': 'Indicador de "Cadastro de Taxas" inválido.',
    'ESCC0396': 'Indicador "Controle de Taxa Máxima" deve ser informado com "Não" quando o "Indicador de obrigatoriedade do Cadastro de Taxas" for igual a "Não".',
    'ESCC0397': 'Indicador "Controle de Taxa Máxima" inválido.',
    'ESCC0398': '"Valor Máximo de Taxa" não deve ser informado quando o "Indicador de Controle de Taxa Máxima" for igual a "Não".',
    'ESCC0399': 'Indicador "Valor Máximo de Taxa" deve ser informado quando o Indicador de "Controle de',
    'ESCC0400': 'Indicador " Permite exibir espécie no simulador e realizar intenção de contratação?" não deve ser informado quando o "Indicador de obrigatoriedade do Cadastro de Taxas" for',
    'ESCC0401': 'Indicador " Permite exibir espécie no simulador e realizar intenção de contratação?"',
    'ESCC0402': 'Indicador "Permite Refinanciamento" inválido.',
    'ESCC0403': 'Quantidade mínima de parcelas processadas para Refinanciamento não deve ser',
    'ESCC0404': 'Quantidade mínima de parcelas processadas para refinanciamento deve ser',
    'ESCC0405': 'Indicador "Permite Alteração Judicial do valor da Averbação" inválido.',
    'ESCC0406': 'Indicador "Permite alteração judicial de valor da averbação sem validação de Margem" deve ser informado com "Não" quando Indicador "Alteração Judicial do Valor da',
    'ESCC0407': 'Indicador "Permite alteração judicial de valor da averbação sem validação de Margem"',
    'ESCC0408': 'Indicador "Tipo de Alteração Judicial de Valor permitida" não deve ser informado quando o',
    'ESCC0409': 'Indicador "Tipo de Alteração Judicial de Valor permitida" inválido.',
    'ESCC0410': 'Indicador "Alteração Judicial da Quantidade de Parcelas" inválido.',
    'ESCC0411': '"Quantidade máxima de parcelas permitidas na alteração judicial" não deve ser informada',
    'ESCC0412': 'Quantidade máxima de parcelas permitidas na alteração judicial deve ser',
    'ESCC0413': 'Indicador "Cadastro do Histórico de Parcelas - Legadas" inválido.',
    'ESCC0414': 'Indicador "Alongamento para Parcelas oriundas do Legado" inválido.',
    'ESCC0415': 'Indicador "Alongamento para parcelas oriundas do Legado" deve ser informado com',
    'ESCC0416': 'Indicador "Cancelamento de Averbações por Não Débito" inválido.',
    'ESCC0417': 'Quantidade de parcelas não debitadas para cancelamento não deve ser informada quando',
    'ESCC0418': 'Quantidade de parcelas não debitadas para cancelamento deve ser informada dentro do intervalo de "1 a 999".',
    'ESCC0419': '"Indicador de permissão para realizar alteração sem Margem" inválido.',
    'ESCC0420': 'Espécie(s) informada(s) deve(m) estar vinculada(s) ao mesmo "Produto" da "Espécie" que está sendo cadastrada.',
    'ESCC0421': 'Identificação do Participante obrigatório.',
    'ESCC0422': 'CNPJ Base do Ente obrigatório.',
    'ESCC0423': 'Espécie obrigatório.',
    'ESCC0424': 'Descrição da Espécie obrigatório.',
    'ESCC0425': 'Produto obrigatório.',
    'ESCC0426': 'Tipo de Parcelamento obrigatório.',
    'ESCC0427': '"Quantidade máxima de Consignações por Servidor" obrigatório.',
    'ESCC0428': '"Quantidade máxima de consignações por Servidor" deve ser informada dentro do',
    'ESCC0429': '"Quantidade máxima de consignações por Consignatário" deve ser informada.',
    'ESCC0430': '"Quantidade máxima de consignações por Consignatário" deve ser informada dentro do',
    'ESCC0431': 'Indicador "Averbar sem Margem" obrigatório.',
    'ESCC0432': 'Indicador "Carência de Início de Débito" obrigatório.',
    'ESCC0433': 'Taxa de Custeio obrigatório.',
    'ESCC0434': 'Ordem de Prioridade obrigatório.',
    'ESCC0435': 'Indicador "Valida Valor Mínimo" obrigatório.',
    'ESCC0436': 'Indicador "Alongamento” obrigatório.',
    'ESCC0437': 'Indicador "Permite alongamento para parcelas oriundas do legado" obrigatório.',
    'ESCC0438': 'Indicador "Débito Parcial" obrigatório.',
    'ESCC0439': 'Indicador " Permite exibir espécie no simulador e realizar intenção de contratação?" deve',
    'ESCC0440': 'Indicador "Permite quantidade de Parcelas e Valor" obrigatório.',
    'ESCC0441': 'Indicador "Cadastro de Taxas" obrigatório.',
    'ESCC0442': 'Indicador "Controle de Taxa Máxima" obrigatório.',
    'ESCC0443': 'Indicador de permissão de Refinanciamento deve ser informado.',
    'ESCC0444': 'Indicador "Permitir Alteração Judicial do valor da Averbação" obrigatório.',
    'ESCC0445': 'Indicador "Alteração Judicial de Valor da Averbação sem validação de Margem"',
    'ESCC0446': 'Indicador "Permite Alteração Judicial da Quantidade de Parcelas" obrigatório.',
    'ESCC0447': 'Indicador "Cadastro do Histórico de Parcelas - Legadas" obrigatório.',
    'ESCC0448': 'Indicador " Cancelamento de Averbações por Não Débito" obrigatório.',
    'ESCC0449': 'Data de Recadastramento deve ser maior ou igual à Data atual.',
    'ESCC0450': 'CNPJ do Consignatário obrigatório.',
    'ESCC0451': 'Número do Consignatário no Ente obrigatório.',
    'ESCC0452': 'Quantidade Máxima de Espécies permitidas obrigatório.',
    'ESCC0453': 'Data de início de vigência da espécie obrigatório.',
    'ESCC0454': 'Data de Início de Vigência da Espécie inválida.',
    'ESCC0455': 'Data de Início de vigência da Espécie deve maior ou igual à Data atual.',
    'ESCC0456': 'Participante sem Adesão à funcionalidade.',
    'ESCC0457': 'Participante informado não é o emissor do arquivo.',
    'ESCC0458': 'Quantidade máxima de Espécies permitidas para o Consignatário deve ser menor ou igual à quantidade estabelecida no Arranjo ativo do Ente.',
    'ESCC0459': 'Data de Fim de Mandato deve ser maior ou igual à data atual.',
    'ESCC0460': 'Data de Auditoria deve ser maior ou igual à data atual.',
    'ESCC0461': 'Indicador "Perda de Prioridade" inválido.',
    'ESCC0462': 'Espécie(s) não deve(m) ser informada(s) quando o "Indicador Permite Refinanciamento"',
    'ESCC0463': 'Registro da averbação não autorizado pelo Órgão.',
    'ESCC0464': 'Número da Averbação Legado não deve ser informado para Tipo de Operação igual a "1 -',
    'ESCC0465': 'Situação da Carga do Legado não permite o registro do Histórico de Parcelas.',
    'ESCC0466': 'Situação da Carga do Legado não permite o registro dos meses de Janelamento.',
    'ESCC0467': 'Motivo da carga da averbação oriunda do Legado obrigatório.',
    'ESCC0468': 'Situação do Consignatário na CIP não permite um novo cadastro.',
    'ESCC0469': 'Natureza informada não permitida. Consignatário já encontra-se cadastrado na CIP com',
    'ESCC0470': 'Não é permitido ao Órgão alterar ou excluir uma operação incluída pelo Consignatário.',
    'ESCC0472': 'Taxa Nominal informada na averbação não pode ser maior do que a taxa máxima',
    'ESCC0473': 'Taxa CET informada na averbação não pode ser maior do que a taxa máxima informada no cadastro vigente.',
    'ESCC0474': 'Operação não realizada. Calendário de processamento não cadastrado.',
    'ESCC0475': 'Dados bancários inválidos.',
    'ESCC0476': 'Espécie não permite conta portada.',
    'ESCC0477': 'Número do banco não confere com o cadastrado pela folha.',
    'ESCC0478': 'Número da agência não confere com o cadastrado pela folha de Pagamento.',
    'ESCC0479': 'Número da conta não confere com o cadastrado pela folha de pagamento.',
    'ESCC0480': 'Número do dígito da conta não confere com o cadastrado pela folha de pagamento.',
    'ESCC0481': 'Averbação não efetuada. Dados bancários não cadastrados.',
    'ESCC0482': 'Margem não cadastrada.',
    'ESCC0483': 'Verba fixa inválida. Escolha entre S para “Sim” e N para “Não”.',
    'ESCC0484': 'Tipo de rubrica inválido.',
    'ESCC0485': 'Margem não cadastrada para a identificação e Mês/Ano de Referência.',
    'ESCC0486': 'Consulta de Margem não autorizada pelo Servidor.',
    'ESCC0487': 'Ente não permite exibir margem.',
    'ESCC0488': 'Não existe Composição da Margem cadastrada para a Identificação e Mês/Ano de',
    'ESCC0489': 'Ente não permite exibir Composição de Margem.',
    'ESCC0490': 'Consulta de Composição da Margem não autorizada pelo Servidor.',
    'ESCC0491': 'Números das averbações informadas pertencem a um servidor cadastrado em Órgão e',
    'ESCC0492': 'Números das averbações informadas pertencem a um servidor cadastrado em Órgãos',
    'ESCC0493': 'Números das averbações informadas pertencem a um servidor cadastrado em Matrículas',
    'ESCC0494': 'Mês/Ano de Referência da Margem informado diferente do Mês/Ano de Referência cadastrada no calendário.',
    'ESCC0495': 'Data está fora do calendário de processamento.',
    'ESCC0496': 'Indicador "Permite Informar Dados de Conta Portada" deve ser informado quando o indicador "Habilita Validação de Dados Bancários" igual à "Sim".',
    'ESCC0497': 'Indicador "Permite Informar Dados de Conta Portada" não deve ser igual a Sim quando o',
    'ESCC0498': 'Não foi possível realizar a conciliação. Informações insuficientes.',
    'ESCC0499': 'Não foram identificadas parcelas pendentes de conciliação para a averbação.',
    'ESCC0500': 'Não foi localizada uma parcela para o número único da averbação e Mês/Ano.',
    'ESCC0501': 'Indicador "Permite Transferência de Averbação" obrigatório.',
    'ESCC0502': 'Indicador "Permite Transferência de Averbação" inválido.',
    'ESCC0503': 'Espécie(s) permitidas na Transferência de Averbação não deve(m) ser informada(s) quando',
    'ESCC0504': 'Indicador "Perde Prioridade de Desconto na Transferência de Averbação" obrigatório.',
    'ESCC0505': 'Indicador "Perde Prioridade de Desconto na Transferência de Averbação" inválido.',
    'ESCC0506': 'Indicador "Permite alterar o número do contrato" obrigatório.',
    'ESCC0507': 'Indicador "Permite alterar o número do contrato" inválido.',
    'ESCC0508': 'Não existe autorização Ativa para o número da Averbação.',
    'ESCC0509': 'Não existem Autorizações Ativas para a(s) matrícula(s) ou identificação(ões) localizada(s).',
    'ESCC0510': 'Situação da Averbação informada não permite Transferência.',
    'ESCC0511': 'Situação da(s) Averbação(ões) Autorizada(s) não permite Transferência.',
    'ESCC0512': 'Não existe autorização "Ativa" vinculada ao Consignatário para o Número da Averbação',
    'ESCC0513': 'Não existem Autorizações "Ativas" vinculadas ao Consignatário para a(s) matricula(s) ou',
    'ESCC0514': 'Averbação informada já está sendo utilizada em outro processo de Transferência.',
    'ESCC0515': 'Existem Averbação(ões) Autorizada(s) que já está(ão) sendo utilizada(s) em outro processo',
    'ESCC0516': 'Não foi localizado o Servidor/Provimento para o Órgão informado.',
    'ESCC0517': 'Mês de Referência da Margem informado não permitido para o Órgão.',
    'ESCC0518': 'O indicador "Perde Prioridade de Desconto na Transferência de Averbação" não deve ser informado quando o campo indicador "Permite Transferência de Averbação" for igual a',
    'ESCC0520': 'Transferência não permitida. Identificação de origem e destino com quantidade de margens diferentes.',
    'ESCC0521': 'Obrigatório informar o CPF ou Identificação (matrícula).',
    'ESCC0522': 'Averbação em situação de "reserva de negociação de transferência".',
    'ESCC0523': 'Averbação em situação de "Reserva de margem de transferência".',
    'ESCC0524': 'Reserva de margem cancelada por Averbação Origem',
    'ESCC0525': 'Matricula ou Identificação localizada(s) não está(ão) habilitada(s) para realizar a',
    'ESCC0526': 'Não foram encontradas Averbações Autorizadas em condições de Transferência.',
    'ESCC0527': 'Identificação da Espécie informada não permite transferência de averbação.',
    'ESCC0528': 'Contrato com Alteração Judicial',
    'ESCC0529': 'Contrato com averbação em situação de reserva de Refinanciamento.',
    'ESCC0530': 'Não há "Situação Cadastral" definida pelo Órgão como situação padrão de transferência',
    'ESCC0531': 'Indicador "Permite Renegociação" obrigatório.',
    'ESCC0532': 'Indicador de permissão "Renegociação" inválido.',
    'ESCC0533': 'Quantidade Máxima de Parcelas na Renegociação não deve ser informada para indicador de "Permite Renegociação" igual a "Não".',
    'ESCC0534': 'Quantidade Máxima de Parcelas na Renegociação deve ser informada dentro do intervalo',
    'ESCC0535': 'Quantidade Máxima de Parcelas na Renegociação deve maior ou igual ao Parcelamento',
    'ESCC0536': 'Quantidade Máxima de Parcelas na Renegociação não deve ser informada quando o “Tipo',
    'ESCC0537': 'Quantidade Máxima de Parcelas na Renegociação deve ser igual à “1” quando o “Tipo de Parcelamento” igual à “Único”',
    'ESCC0538': 'Situação da Averbação não permite a Renegociação.',
    'ESCC0539': 'Espécie da Averbação não Permite Renegociação.',
    'ESCC0540': 'Para realizar uma Renegociação ao menos uma das condições da Averbação precisa ser',
    'ESCC0541': 'Valor da Parcela da Renegociação deve ser menor ou igual ao Valor atual da Parcela na Averbação.',
    'ESCC0542': 'Quantidade Total de Parcelas na Renegociação deve ser maior que a Quantidade de Parcelas já Processadas.',
    'ESCC0543': 'Quantidade Total de Parcelas deve ser menor ou igual à quantidade máxima de parcelas',
    'ESCC0547': 'Indicador "Permite Servidor optar pela reserva de margem na intenção da contratação?" obrigatório quando "Permite exibir espécie no simulador e realizar intenção de',
    'ESCC0548': 'Indicador "Permite Servidor optar pela reserva de margem na intenção da contratação?" não deve ser igual a Sim quando o indicador "Permite exibir espécie no simulador e',
    'ESCC0549': 'Não há calendário do arquivo SCC036 cadastrado para o Mês de Referência do Órgão.',
    'ESCC0550': 'Indicador “Permite Servidor optar pela reserva de margem na intenção da contratação?” não deve ser informado quando o “Indicador de obrigatoriedade de Cadastro de Taxas” for',
    'ESCC0551': 'Indicador "Exige Autorização do Servidor para Efetivação da Operação" obrigatório.',
    'ESCC0552': 'Indicador "Exige Autorização do Servidor para Efetivação da Operação" inválido.',
    'ESCC0553': 'Quantidade de Dias Máxima para Autorização do Servidor não deve ser informada para indicador "Exige Autorização do Servidor para Efetivação da Operação" igual a "Não".',
    'ESCC0554': 'Quantidade de Dias Máxima para Autorização do Servidor deve ser informada dentro do',
    'ESCC0559': 'Espécie não autorizada pelo Órgão.',
    'ESCC0560': 'Operação não permitida, Averbação na situação "Aguardando Autorização do Servidor"',
    'ESCC0561': 'Operação não permitida, Averbação na situação "Não Autorizada pelo Servidor"',
    'ESCC0562': 'Operação não permitida, Averbação na situação "Prazo para Autorização do Servidor',
    'ESCC0563': 'Situação da Averbação não permite cadastro de Prévia.',
    'ESCC0564': 'Número de solicitação de saldo devedor não localizado.',
    'ESCC0565': 'Número de solicitação de saldo devedor não vinculado ao número da averbação',
    'ESCC0566': 'Devolutiva do Saldo Devedor já encaminhada em outro arquivo / mensagem.',
    'ESCC0567': 'Data de vencimento do Saldo Devedor deve ser maior ou igual que a data atual do sistema.',
    'ESCC0568': 'Valor do saldo devedor deve ser maior ou igual à zero.',
    'ESCC0569': 'Não existe averbação para as condições apresentadas.',
    'ESCC0570': 'Situação cadastral do servidor não permite transferência.',
    'ESCC0571': 'Não existe espécie disponível para transferência.',
    'ESCC0572': 'Foram encontradas mais de uma averbação para as condições apresentadas',
    'ESCC0573': 'Não existe reserva de transferência de averbação ativa',
    'ESCC0574': 'Não foi possível cancelar a reserva, averbação já ativa',
    'ESCC0575': 'Transferência não finalizada, averbação destino já ativa',
    'ESCC0576': 'Prazo máximo do contrato superior ao limite permitido pelo Ente para o Servidor.',
    'ESCC0577': 'O tipo de vínculo informado não permite Alongamento.',
    'ESCC0578': 'O tipo de vínculo informado não permite Janelamento.',
    'ESCC0579': 'Já existe um processo de autorização pendente de aprovação pelo Servidor',
    'ESCC0580': 'As consultas já estão autorizadas pelo Servidor.',
    'ESCC0581': 'Ente não permite o envio de autorização de consultas em nome do Servidor.',
    'ESCC0582': 'A data de autorização deve ser menor ou igual a data atual.',
    'ESCC9999': 'Ação não realizada. Entre em contato com o Administrador.',

}
